development:
  adapter: postgresql
  encoding: unicode
  database: heroku_sinatra_app
  pool: 2
  username: oleh_hudak
  password: 123456
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
